### ISSUE TITLE
Notify hanging

### ISSUE THREAD

**Issue by jeremycherfas** [Perlkonig/grav-plugin-webmention#8]
When I run `bin/plugin webmention notify` in Terminal, it just hangs at the end. As it happens, the final target is returning `HTTP/1.1 400 Bad Request` but that shouldn't stop the processing, should it?

**Comment by Perlkonig** [comment]
I'm so sorry this fell through the cracks. I try really hard to keep on top of GitHub issues. Are you still having this problem? It shouldn't hang forever, no. I tested with all sorts of different URLs.

Because this is old, I'm going to go ahead and close it, but please respond if this persists and we'll do some troubleshooting.
